data = {
  data: [
    {
      id: 2,
      documentId: 'cft74w53fcsoytxkh4ve2ijx',
      name: 'Alexander Samuel',
      description: "Alexander III of Macedon (Ancient Greek: Ἀλέξανδρος, romanized: Alexandros; 20/21 July 356 BC – 10/11 June 323 BC), most commonly known as Alexander the Great,[c] was a king of the ancient Greek kingdom of Macedon.[d] He succeeded his father Philip II to the throne in 336 BC at the age of 20 and spent most of his ruling years conducting a lengthy military campaign throughout Western Asia, Central Asia, parts of South Asia, and Egypt. By the age of 30, he had created one of the largest empires in history, stretching from Greece to northwestern India.[1] He was undefeated in battle and is widely considered to be one of history's greatest and most successful military commanders.[2][3][4]\n\nUntil the age of 16, Alexander was tutored by Aristotle. In 335 BC, shortly after his assumption of kingship over Macedon, he campaigned in the Balkans and reasserted control over Thrace and parts of Illyria before marching on the city of Thebes, which was subsequently destroyed in battle. Alexander then led the League of Corinth, and used his authority to launch the pan-Hellenic project envisaged by his father, assuming leadership over all Greeks in their conquest of Persia.[5][6]",
      slug: 'alexander-samuel',
      createdAt: '2024-11-16T14:54:42.098Z',
      updatedAt: '2024-11-16T14:54:42.098Z',
      publishedAt: '2024-11-16T14:54:42.114Z',
      locale: null,
      photo: {
        id: 1,
        documentId: 'ezmnpa34ul9m11j202nh6z8a',
        name: 'freepik_image2.png',
        alternativeText: null,
        caption: null,
        width: 500,
        height: 500,
        formats: {
          thumbnail: {
            name: 'thumbnail_freepik_image2.png',
            hash: 'thumbnail_freepik_image2_fda317591d',
            ext: '.png',
            mime: 'image/png',
            path: null,
            width: 156,
            height: 156,
            size: 27.05,
            sizeInBytes: 27045,
            url: '/uploads/thumbnail_freepik_image2_fda317591d.png',
          },
        },
        hash: 'freepik_image2_fda317591d',
        ext: '.png',
        mime: 'image/png',
        size: 71.08,
        url: '/uploads/freepik_image2_fda317591d.png',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        createdAt: '2024-11-16T14:54:27.014Z',
        updatedAt: '2024-11-16T14:54:27.014Z',
        publishedAt: '2024-11-16T14:54:27.016Z',
        locale: null,
      },
      localizations: [],
    },
    {
      id: 4,
      documentId: 'gwgychj7ktjkbjtak2u07uxg',
      name: 'Jeba Alexander',
      description: 'In 334 BC, he invaded the Achaemenid Persian Empire and began a series of campaigns that lasted for 10 years. Following his conquest of Asia Minor, Alexander broke the power of Achaemenid Persia in a series of decisive battles, including those at Issus and Gaugamela; he subsequently overthrew Darius III and conquered the Achaemenid Empire in its entirety.[e] After the fall of Persia, the Macedonian Empire held a vast swath of territory between the Adriatic Sea and the Indus River. Alexander endeavored to reach the "ends of the world and the Great Outer Sea" and invaded India in 326 BC, achieving an important victory over Porus, an ancient Indian king of present-day Punjab, at the Battle of the Hydaspes. Due to the mutiny of his homesick troops, he eventually turned back at the Beas River and later died in 323 BC in Babylon, the city of Mesopotamia that he had planned to establish as his empire\'s capital. Alexander\'s death left unexecuted an additional series of planned military and mercantile campaigns that would have begun with a Greek invasion of Arabia. In the years following his death, a series of civil wars broke out across the Macedonian Empire, eventually leading to its disintegration at the hands of the Diadochi.',
      slug: 'jeba-alexander',
      createdAt: '2024-11-16T14:55:53.389Z',
      updatedAt: '2024-11-16T14:55:53.389Z',
      publishedAt: '2024-11-16T14:55:53.405Z',
      locale: null,
      photo: {
        id: 2,
        documentId: 'psdyziirgfhlxn3t8csk4qgu',
        name: 'demo_img1.png',
        alternativeText: null,
        caption: null,
        width: 500,
        height: 500,
        formats: {
          thumbnail: {
            name: 'thumbnail_demo_img1.png',
            hash: 'thumbnail_demo_img1_ee73ec2784',
            ext: '.png',
            mime: 'image/png',
            path: null,
            width: 156,
            height: 156,
            size: 64.35,
            sizeInBytes: 64353,
            url: '/uploads/thumbnail_demo_img1_ee73ec2784.png',
          },
        },
        hash: 'demo_img1_ee73ec2784',
        ext: '.png',
        mime: 'image/png',
        size: 127.1,
        url: '/uploads/demo_img1_ee73ec2784.png',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        createdAt: '2024-11-16T14:55:42.801Z',
        updatedAt: '2024-11-16T14:55:42.801Z',
        publishedAt: '2024-11-16T14:55:42.803Z',
        locale: null,
      },
      localizations: [],
    },
    {
      id: 6,
      documentId: 'z499teucanpt9lz2steim5zs',
      name: 'Joselyn Alexander',
      description: "Alexander became legendary as a classical hero in the mould of Achilles, featuring prominently in the historical and mythical traditions of both Greek and non-Greek cultures. His military achievements and unprecedented enduring successes in battle made him the measure against which many later military leaders would compare themselves,[f] and his tactics remain a significant subject of study in military academies worldwide.[7] Legends of Alexander's exploits coalesced into the third-century Alexander Romance which, in the premodern period, went through over one hundred recensions, translations, and derivations and was translated into almost every European vernacular and every language of the Islamic world.[8] After the Bible, it was the most popular form of European literature.[9]",
      slug: 'joselyn-alexander',
      createdAt: '2024-11-16T14:56:48.972Z',
      updatedAt: '2024-11-16T14:56:48.972Z',
      publishedAt: '2024-11-16T14:56:48.989Z',
      locale: null,
      photo: {
        id: 3,
        documentId: 'epq2mc7ow7ihm6h264srfqt8',
        name: 'freepik_image1.png',
        alternativeText: null,
        caption: null,
        width: 500,
        height: 500,
        formats: {
          thumbnail: {
            name: 'thumbnail_freepik_image1.png',
            hash: 'thumbnail_freepik_image1_c83a089ac9',
            ext: '.png',
            mime: 'image/png',
            path: null,
            width: 156,
            height: 156,
            size: 36.71,
            sizeInBytes: 36711,
            url: '/uploads/thumbnail_freepik_image1_c83a089ac9.png',
          },
        },
        hash: 'freepik_image1_c83a089ac9',
        ext: '.png',
        mime: 'image/png',
        size: 98.73,
        url: '/uploads/freepik_image1_c83a089ac9.png',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        createdAt: '2024-11-16T14:56:43.400Z',
        updatedAt: '2024-11-16T14:56:43.400Z',
        publishedAt: '2024-11-16T14:56:43.401Z',
        locale: null,
      },
      localizations: [],
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 25,
      pageCount: 1,
      total: 3,
    },
  },
}
