import Link from 'next/link'
import Footer from '../components/Footer'

import '../assets/global.css'
import NavLink from '../components/NavLink'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <div className="absolute z-0 inset-0 overflow-hidden">
            <div className="circle-one blur-3xl w-64 h-64 rounded-full bg-rose-400/60 top-0 right-28 absolute"></div>
            <div className="circle-two blur-3xl w-64 h-64 rounded-full bg-indigo-400/60 bottom-0 left-28 absolute"></div>
          </div>
          {/* Header */}
          <header className="bg-white/50 z-10 backdrop-blur">
            <div className="max-w-4xl mx-auto flex items-center justify-between">
              <h2 className="text-gray-500 py-4">Ramapuaram Corporate Fellowship</h2>
              <nav>
                <ul className="flex gap-x-7 text-sm text-gray-500">
                  <li>
                    <NavLink href="/" text="Home" />
                  </li>
                  <li>
                    <NavLink href="/our-team" text="Our Team" />
                  </li>
                  <li>
                    <NavLink href="/about-us" text="About Us" />
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          {/* Main Content */}
          <main className="max-w-4xl mx-auto bg-white/50 rounded-xl py-7 px-8 m-6 overflow-hidden z-10 backdrop-blur">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  )
}
